### ISSUE TITLE
Release 21

### ISSUE THREAD

**Issue by gundelsby** [nrkno/Sofie-TV-automation#17]
_In the Sofie-project at NRK we work in sprints, generally 2-3 weeks long and we'll communicate the status of each release here. The releases are also documented [here](https://sofie.gitbook.io/sofie-tv-automation/documentation/releases)._

_Note: This issue is subject to change and will be updated as development progresses._

The contents of this release is not planned yet, more updates will follow.

## Development status

The development is expected to start in the beginning of May.

- [x] Planning
- [x] Working on
- [x] Features frozen, in testing.  
- [ ] Tests complete, update docs
- [ ] Released

## Summary of features

* Media manager no longer requires a separate media scanner (http://github.com/nrkno/tv-automation-server-core/pull/165)
* Performance improvements for long shows (http://github.com/nrkno/tv-automation-server-core/pull/220)
* Buckets & MOS plugins in ExternalFrames in dashboard (http://github.com/nrkno/tv-automation-server-core/pull/195)
* Contributions from TV2 (http://github.com/nrkno/tv-automation-server-core/pull/222)
* Fix to wrong ordering of parts (http://github.com/nrkno/tv-automation-server-core/pull/227)

## Expected versions of components:
| Component | Expected version |
| -- | -- |
| [Core](https://bit.ly/2yFZA9X) | 1.9.0 |
| [Blueprints API ( Core )](https://bit.ly/2YtWk0L) | 1.12.0 |
| [Blueprints API ( TSR )](https://bit.ly/2GTAmcF) | 3.20.1 |
| [Playout Gateway](https://bit.ly/2OKGbzn) | 1.8.0 |
| [Mos Gateway](https://bit.ly/2Tc1wR1) | 1.3.2 |
| [Spreadsheet Gateway](https://bit.ly/2KB0iL9) | TBD |
| [Media Manager](https://bit.ly/2ZDRjiD) | 1.2.0 |

**Comment by nytamin** [comment]
This release was never released, see [Release 22](https://github.com/nrkno/Sofie-TV-automation/issues/18) instead
