### ISSUE TITLE
Release 22 [BREAKING]

### ISSUE THREAD

**Issue by sparkpunkd** [nrkno/Sofie-TV-automation#18]
_In the Sofie-project at NRK we work in sprints, generally 2-3 weeks long and we'll communicate the status of each release here. The releases are also documented [here](https://sofie.gitbook.io/sofie-tv-automation/documentation/releases)._

_Note: This issue is subject to change and will be updated as development progresses._

The contents of this release is not planned yet, more updates will follow.

## Development status

Testing is expected to start 2020-06-15.

- [x] Planning
- [x] Working on
- [x] Features frozen, in testing.  
- [x] Tests complete, update docs
- [x] Released

## Summary of features

This release features an update of the Meteor platform, from 1.6 to 1.10, which is a large jump ahead. This requires mongodb to be updated, from the old 3.6 to 4.2. Update instructions are [posted below](https://github.com/nrkno/Sofie-TV-automation/issues/18#issuecomment-644631314).

_To be announced_

## Expected versions of components:
| Component | Expected version |
| -- | -- |
| [Core](https://bit.ly/2yFZA9X) | 1.10.0 |
| [Blueprints API ( Core )](https://bit.ly/2YtWk0L) | TBD |
| [Blueprints API ( TSR )](https://bit.ly/2GTAmcF) | 4.0.0 |
| [Playout Gateway](https://bit.ly/2OKGbzn) | 1.9.0 |
| [Mos Gateway](https://bit.ly/2Tc1wR1) | 1.4.x |
| [Spreadsheet Gateway](https://bit.ly/2KB0iL9) | - |
| [Media Manager](https://bit.ly/2ZDRjiD) | 1.2.0 |

**Comment by nytamin** [comment]
Regarding updating mongodb:
This is the script that NRK used for updating mongodb from 3.6 to 4.2, to draw inspiration from:
```
#!/bin/bash
docker stop mongo
docker rm mongo
docker run --network sofie --name=mongo --hostname=mongodb --volume=/opt/mongo/db:/data/db --volume=/opt/mongo/backup:/data/backup --volume=/etc/timezone:/etc/timezone:ro -p 127.0.0.1:27017:27017 --detach=true mongo:3.6.18 mongod --replSet rs0
sleep 5
docker exec -it mongo mongo --eval  'db.adminCommand( { setFeatureCompatibilityVersion: "3.6" } )'
docker stop mongo
docker rm mongo
docker run --network sofie --name=mongo --hostname=mongodb --volume=/opt/mongo/db:/data/db --volume=/opt/mongo/backup:/data/backup --volume=/etc/timezone:/etc/timezone:ro -p 127.0.0.1:27017:27017 --detach=true mongo:4.0.18 mongod --replSet rs0
sleep 5
docker exec -it mongo mongo --eval  'db.adminCommand( { setFeatureCompatibilityVersion: "4.0" } )'
docker stop mongo
docker rm mongo
docker run --network sofie --name=mongo --hostname=mongodb --volume=/opt/mongo/db:/data/db --volume=/opt/mongo/backup:/data/backup --volume=/etc/timezone:/etc/timezone:ro -p 127.0.0.1:27017:27017 --detach=true mongo:4.2.7 mongod --replSet rs0
sleep 5
docker exec -it mongo mongo --eval  'db.adminCommand( { setFeatureCompatibilityVersion: "4.2" } )'
```

**Comment by jesperstarkar** [comment]
I don't know if it's _this_ script, but something regarding the upgrade has a flaw where autorestart on server reboot i broken.

**Comment by Julusian** [comment]
@jesperstarkar The last `docker run ...` probably just needs `--restart always` added into it. Or possibly some other mode, depending on what was previously used

**Comment by jesperstarkar** [comment]
Sounds likely since the manual patch is to run `"docker update --restart=always mongo"`
