### ISSUE TITLE
Sofie server core basic configuration

### ISSUE THREAD

**Issue by vkosh** [nrkno/Sofie-TV-automation#2]
Hello,

I'm trying to prepare basic setup of Sofie system with CasparCG playout device. I have installed Sofie Server Core, Sofie Playout Gateway and Caspar CG Server. Everything seems to work except that "Running orders" page has no items, and there is no possibility to add anything in UI.

Could you explain if this [GUI](https://raw.githubusercontent.com/nrkno/Sofie-TV-automation/master/Sofie_GUI_example.jpg) is produced by Sofie Server Core or some other software (proprietary?), what Running Orders are and how I can edit them? Is there any documentation to read?

Thank you.

**Comment by mint-dewit** [comment]
Hi,

We are still working on a guide on how to set up _everything_.

The UI you are referring to is indeed Sofie Server Core and is completely open source. Currently Sofie requires a rundown to come from a MOS enabled NRCS (news room control system). This data will flow through something called blueprints, a set of scripts that transform the MOS data from the NRCS into a Sofie rundown. At the moment we are not aware of an open source MOS enabled NRCS, nor have we published an open source set of blueprints. Though the latter is planned to be released together with the guide.

Kind regards.

**Comment by hummelstrand** [comment]
There are plans for a public wiki, a complete setup guide, and a set of boilerplate Blueprints, but we have not committed to a time plan for these. As of today, the Blueprints are the only part of the Sofie system that have not been posted publicly (as the Blueprints we've created for the installation at NRK currently contain some business logic).

**Comment by vkosh** [comment]
Thaks a lot for the explanation.
