### ISSUE TITLE
docker-compose.yaml refers to non-existent docker image 

### ISSUE THREAD

**Issue by jklq** [nrkno/Sofie-TV-automation#27]
In one of the commented out sections in the docker-compose file you provide at https://sofie.gitbook.io/sofie-tv-automation/documentation/getting-started/installation/installing-sofie-server-core you link to `superflytv/sofie-spreadsheet-gateway:master` while only `superflytv/sofie-spreadsheet-gateway:develop` exists at [Docker Hub](https://hub.docker.com/r/superflytv/sofie-spreadsheet-gateway/tags). This produced an error for me, and changing the link to `superflytv/sofie-spreadsheet-gateway:develop` fixed it.

**Comment by nytamin** [comment]
Thanks for bringing this to our attention, I've updated the docs to point to the develop tag.
