### ISSUE TITLE
Is the installation process going to become more documented/automated?

### ISSUE THREAD

**Issue by jklq** [nrkno/Sofie-TV-automation#28]
Currently I have a hard time installing the software. Especially updating/migrating the database at the start (I don't know what "media previews url" is referring to for example). The docs for that are [here](https://sofie.gitbook.io/sofie-tv-automation/documentation/getting-started/installation/initial-sofie-core-setup). Do you have plans to expand the documentation or make the installation more straight forward through other means (for example more automation)?.

**Comment by Keksstar** [comment]
+1

**Comment by nytamin** [comment]
We are continuously working on improving the documentation, although our main efforts are focused on areas that are used by NRK.
We gladly accept Pull Requests though. Now that [we've moved the documentation](https://nrkno.github.io/sofie-core/docs/getting-started/intro) to the [Core mono repo](https://github.com/nrkno/sofie-core/tree/master/packages/documentation) it should be much easier to contribute documentation-updates, the same way as code contributions.
