### ISSUE TITLE
check databaseVersion mismatch - 1.17.0-in-testing-R29.1

### ISSUE THREAD

**Issue by dev-clavis** [nrkno/Sofie-TV-automation#30]
I just tried to install Sofie with the docker-compose.yaml from https://sofie.gitbook.io/sofie-tv-automation/documentation/getting-started/installation/installing-sofie-server-core
`
There are no rundowns ingested into Sofie.

Sofie Automation version: 1.17.0-in-testing-R29.1

System Status: FAIL / BAD
Status Messages:
check databaseVersion: Version mismatch: core version: "1.17.0" does not satisfy expected version of system database: "0.0.0" (to fix, run migration)`

* How do I run migration?
* Do i need to have already rundowns installed to that point?

Thank you

**Comment by dev-clavis** [comment]
Attaching to sofie_db_1, sofie_core_1, sofie_playout-gateway_1
[33mdb_1               |[0m 2021-02-08T15:18:20.717+0000 I  CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
[33mdb_1               |[0m 2021-02-08T15:18:20.721+0000 W  ASIO     [main] No TransportLayer configured during NetworkInterface startup
[33mdb_1               |[0m 2021-02-08T15:18:20.722+0000 I  CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=mongo
[33mdb_1               |[0m 2021-02-08T15:18:20.722+0000 I  CONTROL  [initandlisten] db version v4.2.8
[33mdb_1               |[0m 2021-02-08T15:18:20.722+0000 I  CONTROL  [initandlisten] git version: 43d25964249164d76d5e04dd6cf38f6111e21f5f
[33mdb_1               |[0m 2021-02-08T15:18:20.722+0000 I  CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
[33mdb_1               |[0m 2021-02-08T15:18:20.722+0000 I  CONTROL  [initandlisten] allocator: tcmalloc
[33mdb_1               |[0m 2021-02-08T15:18:20.722+0000 I  CONTROL  [initandlisten] modules: none
[33mdb_1               |[0m 2021-02-08T15:18:20.722+0000 I  CONTROL  [initandlisten] build environment:
[33mdb_1               |[0m 2021-02-08T15:18:20.722+0000 I  CONTROL  [initandlisten]     distmod: ubuntu1804
[33mdb_1               |[0m 2021-02-08T15:18:20.722+0000 I  CONTROL  [initandlisten]     distarch: x86_64
[33mdb_1               |[0m 2021-02-08T15:18:20.722+0000 I  CONTROL  [initandlisten]     target_arch: x86_64
[33mdb_1               |[0m 2021-02-08T15:18:20.722+0000 I  CONTROL  [initandlisten] options: { net: { bindIp: "*" } }
[33mdb_1               |[0m 2021-02-08T15:18:20.724+0000 I  STORAGE  [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
[33mdb_1               |[0m 2021-02-08T15:18:20.724+0000 I  STORAGE  [initandlisten] 
[33mdb_1               |[0m 2021-02-08T15:18:20.724+0000 I  STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
[33mdb_1               |[0m 2021-02-08T15:18:20.724+0000 I  STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
[33mdb_1               |[0m 2021-02-08T15:18:20.724+0000 I  STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=1454M,cache_overflow=(file_max=0M),session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000,close_scan_interval=10,close_handle_minimum=250),statistics_log=(wait=0),verbose=[recovery_progress,checkpoint_progress],
[33mdb_1               |[0m 2021-02-08T15:18:23.293+0000 I  STORAGE  [initandlisten] WiredTiger message [1612797503:293832][1:0x7f9dc5712b00], txn-recover: Recovering log 2 through 3
[33mdb_1               |[0m 2021-02-08T15:18:23.693+0000 I  STORAGE  [initandlisten] WiredTiger message [1612797503:693031][1:0x7f9dc5712b00], txn-recover: Recovering log 3 through 3
[33mdb_1               |[0m 2021-02-08T15:18:24.231+0000 I  STORAGE  [initandlisten] WiredTiger message [1612797504:231012][1:0x7f9dc5712b00], txn-recover: Main recovery loop: starting at 2/37248 to 3/256
[33mdb_1               |[0m 2021-02-08T15:18:24.964+0000 I  STORAGE  [initandlisten] WiredTiger message [1612797504:964775][1:0x7f9dc5712b00], txn-recover: Recovering log 2 through 3
[32mplayout-gateway_1  |[0m yarn run v1.22.5
[33mdb_1               |[0m 2021-02-08T15:18:25.313+0000 I  STORAGE  [initandlisten] WiredTiger message [1612797505:313632][1:0x7f9dc5712b00], txn-recover: Recovering log 3 through 3
[32mplayout-gateway_1  |[0m $ node dist/index.js -host core -port 3000
[33mdb_1               |[0m 2021-02-08T15:18:25.946+0000 I  STORAGE  [initandlisten] WiredTiger message [1612797505:946673][1:0x7f9dc5712b00], txn-recover: Set global recovery timestamp: (0, 0)
[33mdb_1               |[0m 2021-02-08T15:18:26.077+0000 I  RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0)
[33mdb_1               |[0m 2021-02-08T15:18:26.220+0000 I  STORAGE  [initandlisten] Timestamp monitor starting
[33mdb_1               |[0m 2021-02-08T15:18:26.223+0000 I  CONTROL  [initandlisten] 
[33mdb_1               |[0m 2021-02-08T15:18:26.223+0000 I  CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
[33mdb_1               |[0m 2021-02-08T15:18:26.223+0000 I  CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
[33mdb_1               |[0m 2021-02-08T15:18:26.223+0000 I  CONTROL  [initandlisten] 
[33mdb_1               |[0m 2021-02-08T15:18:26.537+0000 I  SHARDING [initandlisten] Marking collection local.system.replset as collection version: <unsharded>
[33mdb_1               |[0m 2021-02-08T15:18:26.558+0000 I  STORAGE  [initandlisten] Flow Control is enabled on this deployment.
[33mdb_1               |[0m 2021-02-08T15:18:26.559+0000 I  SHARDING [initandlisten] Marking collection admin.system.roles as collection version: <unsharded>
[33mdb_1               |[0m 2021-02-08T15:18:26.559+0000 I  SHARDING [initandlisten] Marking collection admin.system.version as collection version: <unsharded>
[33mdb_1               |[0m 2021-02-08T15:18:26.571+0000 I  SHARDING [initandlisten] Marking collection local.startup_log as collection version: <unsharded>
[33mdb_1               |[0m 2021-02-08T15:18:26.572+0000 I  FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
[33mdb_1               |[0m 2021-02-08T15:18:26.583+0000 I  SHARDING [LogicalSessionCacheRefresh] Marking collection config.system.sessions as collection version: <unsharded>
[33mdb_1               |[0m 2021-02-08T15:18:26.587+0000 I  SHARDING [LogicalSessionCacheReap] Marking collection config.transactions as collection version: <unsharded>
[33mdb_1               |[0m 2021-02-08T15:18:26.588+0000 I  NETWORK  [listener] Listening on /tmp/mongodb-27017.sock
[33mdb_1               |[0m 2021-02-08T15:18:26.588+0000 I  NETWORK  [listener] Listening on 0.0.0.0
[33mdb_1               |[0m 2021-02-08T15:18:26.588+0000 I  NETWORK  [listener] waiting for connections on port 27017
[33mdb_1               |[0m 2021-02-08T15:18:27.001+0000 I  SHARDING [ftdc] Marking collection local.oplog.rs as collection version: <unsharded>
[32mplayout-gateway_1  |[0m process started
[32mplayout-gateway_1  |[0m {"level":"info","message":"Logging to Console","localTimestamp":"2021-02-08T15:18:28.182Z","randomId":9235}
[32mplayout-gateway_1  |[0m {"level":"info","message":"------------------------------------------------------------------","localTimestamp":"2021-02-08T15:18:28.184Z","randomId":2577}
[32mplayout-gateway_1  |[0m {"level":"info","message":"Starting Playout Gateway","localTimestamp":"2021-02-08T15:18:28.184Z","randomId":863}
[32mplayout-gateway_1  |[0m {"level":"info","message":"Core:          core:3000","localTimestamp":"2021-02-08T15:18:28.186Z","randomId":8505}
[32mplayout-gateway_1  |[0m {"level":"info","message":"------------------------------------------------------------------","localTimestamp":"2021-02-08T15:18:28.186Z","randomId":8845}
[32mplayout-gateway_1  |[0m {"level":"info","message":"Initializing Process...","localTimestamp":"2021-02-08T15:18:28.189Z","randomId":949}
[32mplayout-gateway_1  |[0m {"level":"info","message":"Process initialized","localTimestamp":"2021-02-08T15:18:28.191Z","randomId":3205}
[32mplayout-gateway_1  |[0m {"level":"info","message":"Initializing Core...","localTimestamp":"2021-02-08T15:18:28.194Z","randomId":6778}
[33mdb_1               |[0m 2021-02-08T15:18:29.528+0000 I  NETWORK  [listener] connection accepted from 172.18.0.3:59862 #1 (1 connection now open)
[33mdb_1               |[0m 2021-02-08T15:18:29.542+0000 I  NETWORK  [conn1] received client metadata from 172.18.0.3:59862 conn1: { driver: { name: "nodejs", version: "3.6.2" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "5.4.0-65-generic" }, platform: "'Node.js v12.20.1, LE (legacy)" }
[33mdb_1               |[0m 2021-02-08T15:18:29.607+0000 I  SHARDING [conn1] Marking collection meteor.users as collection version: <unsharded>
[33mdb_1               |[0m 2021-02-08T15:18:30.475+0000 I  SHARDING [conn1] Marking collection meteor.__dummy_coll_3F9TBBnv5jp7mtWaw as collection version: <unsharded>
[32mplayout-gateway_1  |[0m {"level":"error","message":"Error during initialization:","localTimestamp":"2021-02-08T15:18:31.418Z","randomId":388}
[32mplayout-gateway_1  |[0m {"message":"connect ECONNREFUSED 172.18.0.3:3000","stack":"RequestError: connect ECONNREFUSED 172.18.0.3:3000\n    at ClientRequest.<anonymous> (/opt/playout-gateway/node_modules/got/dist/source/core/index.js:953:111)\n    at Object.onceWrapper (events.js:421:26)\n    at ClientRequest.emit (events.js:326:22)\n    at ClientRequest.origin.emit (/opt/playout-gateway/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)\n    at Socket.socketErrorListener (_http_client.js:427:9)\n    at Socket.emit (events.js:314:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)","name":"RequestError","code":"ECONNREFUSED","request":{"_readableState":{"objectMode":false,"highWaterMark":0,"buffer":{"head":null,"tail":null,"length":0},"length":0,"pipes":null,"pipesCount":0,"flowing":null,"ended":false,"endEmitted":false,"reading":false,"sync":true,"needReadable":false,"emittedReadable":false,"readableListening":false,"resumeScheduled":false,"emitClose":true,"autoDestroy":false,"destroyed":true,"defaultEncoding":"utf8","awaitDrainWriters":null,"multiAwaitDrain":false,"readingMore":false,"decoder":null,"encoding":null},"readable":true,"_events":{"pipe":[null,null],"response":[null,null]},"_eventsCount":8,"_writableState":{"objectMode":false,"highWaterMark":0,"finalCalled":true,"needDrain":false,"ending":true,"ended":true,"finished":false,"destroyed":true,"decodeStrings":true,"defaultEncoding":"utf8","length":0,"writing":false,"corked":0,"sync":true,"bufferProcessing":false,"writecb":null,"writelen":0,"afterWriteTickInfo":null,"bufferedRequest":null,"lastBufferedRequest":null,"pendingcb":1,"prefinished":false,"errorEmitted":true,"emitClose":true,"autoDestroy":false,"bufferedRequestCount":0,"corkedRequestsFree":{"next":null,"entry":null}},"writable":false,"allowHalfOpen":true,"requestInitialized":true,"redirects":[],"retryCount":2,"_progressCallbacks":[],"options":{"method":"GET","retry":{"limit":2,"methods":["GET","PUT","HEAD","DELETE","OPTIONS","TRACE"],"statusCodes":[408,413,429,500,502,503,504,521,522,524],"errorCodes":["ETIMEDOUT","ECONNRESET","EADDRINUSE","ECONNREFUSED","EPIPE","ENOTFOUND","ENETUNREACH","EAI_AGAIN"],"maxRetryAfter":null},"headers":{"user-agent":"got (https://github.com/sindresorhus/got)","accept":"application/json","accept-encoding":"gzip, deflate, br"},"hooks":{"init":[],"beforeRequest":[],"beforeRedirect":[],"beforeRetry":[],"beforeError":[],"afterResponse":[]},"decompress":true,"throwHttpErrors":true,"followRedirect":true,"isStream":false,"responseType":"json","resolveBodyOnly":false,"maxRedirects":10,"prefixUrl":"","methodRewriting":true,"ignoreInvalidCookies":false,"http2":false,"allowGetBody":false,"https":{},"pagination":{"countLimit":null,"backoff":0,"requestLimit":10000,"stackAllItems":true},"cacheOptions":{},"url":{},"username":"","password":"","timeout":{}},"requestUrl":"http://core:3000/sockjs/info","_cannotHaveBody":true,"_noPipe":true},"options":{"$ref":"$[\"request\"][\"options\"]"},"timings":{"start":1612797511413,"socket":1612797511414,"lookup":1612797511414,"error":1612797511415,"phases":{"wait":1,"dns":0,"total":2}},"level":"error","localTimestamp":"2021-02-08T15:18:31.425Z","randomId":7739}
[32mplayout-gateway_1  |[0m {"level":"error","message":"RequestError: connect ECONNREFUSED 172.18.0.3:3000\n    at ClientRequest.<anonymous> (/opt/playout-gateway/node_modules/got/dist/source/core/index.js:953:111)\n    at Object.onceWrapper (events.js:421:26)\n    at ClientRequest.emit (events.js:326:22)\n    at ClientRequest.origin.emit (/opt/playout-gateway/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)\n    at Socket.socketErrorListener (_http_client.js:427:9)\n    at Socket.emit (events.js:314:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)","localTimestamp":"2021-02-08T15:18:31.427Z","randomId":2273}
[32mplayout-gateway_1  |[0m {"level":"info","message":"Shutting down in 10 seconds!","localTimestamp":"2021-02-08T15:18:31.430Z","randomId":9958}
[32mplayout-gateway_1  |[0m {"message":"Cannot read property 'send' of undefined","stack":"TypeError: Cannot read property 'send' of undefined\n    at DDPClient.send (/opt/playout-gateway/node_modules/@sofie-automation/server-core-integration/dist/lib/ddpClient.js:131:25)\n    at DDPClient.call (/opt/playout-gateway/node_modules/@sofie-automation/server-core-integration/dist/lib/ddpClient.js:404:14)\n    at /opt/playout-gateway/node_modules/@sofie-automation/server-core-integration/dist/lib/coreConnection.js:225:32\n    at new Promise (<anonymous>)\n    at CoreConnection.callMethod (/opt/playout-gateway/node_modules/@sofie-automation/server-core-integration/dist/lib/coreConnection.js:207:16)\n    at CoreConnection.setStatus (/opt/playout-gateway/node_modules/@sofie-automation/server-core-integration/dist/lib/coreConnection.js:204:21)\n    at CoreHandler.updateCoreStatus (/opt/playout-gateway/dist/coreHandler.js:386:26)\n    at CoreHandler.destroy (/opt/playout-gateway/dist/coreHandler.js:106:21)\n    at Connector.<anonymous> (/opt/playout-gateway/dist/connector.js:28:42)\n    at Generator.throw (<anonymous>)","level":"error","localTimestamp":"2021-02-08T15:18:31.432Z","randomId":1655}
[33mdb_1               |[0m 2021-02-08T15:18:33.944+0000 I  SHARDING [conn1] Marking collection meteor.externalMessageQueue as collection version: <unsharded>
[33mdb_1               |[0m 2021-02-08T15:18:35.169+0000 I  SHARDING [conn1] Marking collection meteor.studios as collection version: <unsharded>
[33mdb_1               |[0m 2021-02-08T15:18:35.699+0000 I  SHARDING [conn1] Marking collection meteor.meteor_accounts_loginServiceConfiguration as collection version: <unsharded>
[33mdb_1               |[0m 2021-02-08T15:18:35.711+0000 I  NETWORK  [listener] connection accepted from 172.18.0.3:59866 #2 (2 connections now open)
[33mdb_1               |[0m 2021-02-08T15:18:35.713+0000 I  NETWORK  [conn2] received client metadata from 172.18.0.3:59866 conn2: { driver: { name: "nodejs", version: "3.6.2" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "5.4.0-65-generic" }, platform: "'Node.js v12.20.1, LE (legacy)" }
[33mdb_1               |[0m 2021-02-08T15:18:35.746+0000 I  SHARDING [conn2] Marking collection meteor.showStyleBases as collection version: <unsharded>
[33mdb_1               |[0m 2021-02-08T15:18:35.755+0000 I  SHARDING [conn2] Marking collection meteor.showStyleVariants as collection version: <unsharded>
[33mdb_1               |[0m 2021-02-08T15:18:35.764+0000 I  SHARDING [conn2] Marking collection meteor.blueprints as collection version: <unsharded>
[36mcore_1             |[0m {"message":"System time: Updating, using ntp-server \"0.se.pool.ntp.org\"...","level":"info"}
[36mcore_1             |[0m process started
[36mcore_1             |[0m {"message":"Core starting up","level":"info"}
[36mcore_1             |[0m {"message":"Core system version: \"1.17.0\"","level":"info"}
[36mcore_1             |[0m {"message":"Enable garbage-collection by passing --expose_gc to node in prod or set SERVER_NODE_OPTIONS=--expose_gc in dev","level":"warn"}
[36mcore_1             |[0m {"message":"Core package mos-connection version: \"0.9.0\"","level":"info"}
[36mcore_1             |[0m {"message":"Core package superfly-timeline version: \"8.1.2\"","level":"info"}
[36mcore_1             |[0m {"message":"Core package core version: \"1.17.0-in-testing-R29.1\"","level":"info"}
[36mcore_1             |[0m {"message":"Core package timeline-state-resolver-types version: \"5.5.1\"","level":"info"}
[33mdb_1               |[0m 2021-02-08T15:18:35.812+0000 I  SHARDING [conn1] Marking collection meteor.coreSystem as collection version: <unsharded>
[36mcore_1             |[0m {"message":"APM agent inactive","level":"info"}
[36mcore_1             |[0m meteor-elastic-apm is not active
[33mdb_1               |[0m 2021-02-08T15:18:35.859+0000 I  SHARDING [conn2] Marking collection meteor.adLibPieces as collection version: <unsharded>
[33mdb_1               |[0m 2021-02-08T15:18:35.865+0000 I  SHARDING [conn1] Marking collection meteor.bucketAdlibs as collection version: <unsharded>
[33mdb_1               |[0m 2021-02-08T15:18:35.868+0000 I  SHARDING [conn2] Marking collection meteor.bucketAdlibActions as collection version: <unsharded>
[33mdb_1               |[0m 2021-02-08T15:18:35.871+0000 I  SHARDING [conn1] Marking collection meteor.buckets as collection version: <unsharded>
[33mdb_1               |[0m 2021-02-08T15:18:35.875+0000 I  SHARDING [conn2] Marking collection meteor.asRunLog as collection version: <unsharded>
[33mdb_1               |[0m 2021-02-08T15:18:35.882+0000 I  SHARDING [conn1] Marking collection meteor.evaluations as collection version: <unsharded>
[33mdb_1               |[0m 2021-02-08T15:18:35.886+0000 I  SHARDING [conn2] Marking collection meteor.expectedMediaItems as collection version: <unsharded>
[33mdb_1               |[0m 2021-02-08T15:18:35.894+0000 I  SHARDING [conn1] Marking collection meteor.expectedPlayoutItems as collection version: <unsharded>
[33mdb_1               |[0m 2021-02-08T15:18:35.908+0000 I  SHARDING [conn2] Marking collection meteor.ingestDataCache as collection version: <unsharded>
[33mdb_1               |[0m 2021-02-08T15:18:35.911+0000 I  SHARDING [conn1] Marking collection meteor.mediaObjects as collection version: <unsharded>
[33mdb_1               |[0m 2021-02-08T15:18:35.917+0000 I  SHARDING [conn1] Marking collection meteor.mediaWorkFlows as collection version: <unsharded>
[33mdb_1               |[0m 2021-02-08T15:18:35.922+0000 I  SHARDING [conn1] Marking collection meteor.mediaWorkFlowSteps as collection version: <unsharded>
[33mdb_1               |[0m 2021-02-08T15:18:35.930+0000 I  SHARDING [conn2] Marking collection meteor.segments as collection version: <unsharded>
[33mdb_1               |[0m 2021-02-08T15:18:35.935+0000 I  SHARDING [conn2] Marking collection meteor.pieces as collection version: <unsharded>
[33mdb_1               |[0m 2021-02-08T15:18:35.938+0000 I  SHARDING [conn1] Marking collection meteor.rundownBaselineObjs as collection version: <unsharded>
[33mdb_1               |[0m 2021-02-08T15:18:35.941+0000 I  SHARDING [conn2] Marking collection meteor.rundownBaselineAdLibPieces as collection version: <unsharded>
[33mdb_1               |[0m 2021-02-08T15:18:35.948+0000 I  SHARDING [conn1] Marking collection meteor.rundownPlaylists as collection version: <unsharded>
[33mdb_1               |[0m 2021-02-08T15:18:35.953+0000 I  SHARDING [conn2] Marking collection meteor.pieceInstances as collection version: <unsharded>
[33mdb_1               |[0m 2021-02-08T15:18:35.956+0000 I  SHARDING [conn1] Marking collection meteor.adLibActions as collection version: <unsharded>
[33mdb_1               |[0m 2021-02-08T15:18:35.959+0000 I  SHARDING [conn2] Marking collection meteor.rundownBaselineAdLibActions as collection version: <unsharded>
[33mdb_1               |[0m 2021-02-08T15:18:35.962+0000 I  SHARDING [conn1] Marking collection meteor.rundowns as collection version: <unsharded>
[33mdb_1               |[0m 2021-02-08T15:18:35.967+0000 I  SHARDING [conn1] Marking collection meteor.parts as collection version: <unsharded>
[33mdb_1               |[0m 2021-02-08T15:18:35.973+0000 I  SHARDING [conn1] Marking collection meteor.partInstances as collection version: <unsharded>
[33mdb_1               |[0m 2021-02-08T15:18:35.981+0000 I  SHARDING [conn2] Marking collection meteor.peripheralDeviceCommands as collection version: <unsharded>
[33mdb_1               |[0m 2021-02-08T15:18:35.984+0000 I  SHARDING [conn1] Marking collection meteor.peripheralDevices as collection version: <unsharded>
[33mdb_1               |[0m 2021-02-08T15:18:35.991+0000 I  SHARDING [conn2] Marking collection meteor.rundownLayouts as collection version: <unsharded>
[33mdb_1               |[0m 2021-02-08T15:18:35.999+0000 I  SHARDING [conn1] Marking collection meteor.snapshots as collection version: <unsharded>
[33mdb_1               |[0m 2021-02-08T15:18:36.015+0000 I  SHARDING [conn1] Marking collection meteor.userActionsLog as collection version: <unsharded>
[36mcore_1             |[0m {"message":"System time: Setting diff to 0 ms (std. dev: 0.4 ms)","level":"info"}
[32mplayout-gateway_1  |[0m Done in 16.50s.
[35mplayout-gateway_1  |[0m yarn run v1.22.5
[35mplayout-gateway_1  |[0m $ node dist/index.js -host core -port 3000
[35mplayout-gateway_1  |[0m process started
[35mplayout-gateway_1  |[0m {"level":"info","message":"Logging to Console","localTimestamp":"2021-02-08T15:18:44.907Z","randomId":1753}
[35mplayout-gateway_1  |[0m {"level":"info","message":"------------------------------------------------------------------","localTimestamp":"2021-02-08T15:18:44.908Z","randomId":6743}
[35mplayout-gateway_1  |[0m {"level":"info","message":"Starting Playout Gateway","localTimestamp":"2021-02-08T15:18:44.909Z","randomId":7842}
[35mplayout-gateway_1  |[0m {"level":"info","message":"Core:          core:3000","localTimestamp":"2021-02-08T15:18:44.909Z","randomId":832}
[35mplayout-gateway_1  |[0m {"level":"info","message":"------------------------------------------------------------------","localTimestamp":"2021-02-08T15:18:44.910Z","randomId":6997}
[35mplayout-gateway_1  |[0m {"level":"info","message":"Initializing Process...","localTimestamp":"2021-02-08T15:18:44.911Z","randomId":7594}
[35mplayout-gateway_1  |[0m {"level":"info","message":"Process initialized","localTimestamp":"2021-02-08T15:18:44.911Z","randomId":5295}
[35mplayout-gateway_1  |[0m {"level":"info","message":"Initializing Core...","localTimestamp":"2021-02-08T15:18:44.914Z","randomId":6824}
[35mplayout-gateway_1  |[0m {"level":"info","message":"Core Connected!","localTimestamp":"2021-02-08T15:18:45.060Z","randomId":2201}
[35mplayout-gateway_1  |[0m {"level":"info","message":"Core: Setting up subscriptions..","localTimestamp":"2021-02-08T15:18:45.061Z","randomId":727}
[35mplayout-gateway_1  |[0m {"level":"info","message":"DeviceId: BGHH649DAA26J69A5","localTimestamp":"2021-02-08T15:18:45.062Z","randomId":2482}
[36mcore_1             |[0m {"category":"playout","type":"playout","subType":"_process","name":"Playout gateway","connectionId":"ASdL2HyTC5QBxLgqr","level":"debug","message":"Initialize device BGHH649DAA26J69A5"}
[33mdb_1               |[0m 2021-02-08T15:18:45.194+0000 I  NETWORK  [listener] connection accepted from 172.18.0.3:59890 #3 (3 connections now open)
[33mdb_1               |[0m 2021-02-08T15:18:45.195+0000 I  NETWORK  [conn3] received client metadata from 172.18.0.3:59890 conn3: { driver: { name: "nodejs", version: "3.6.2" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "5.4.0-65-generic" }, platform: "'Node.js v12.20.1, LE (legacy)" }
[35mplayout-gateway_1  |[0m {"level":"info","message":"Core id: BGHH649DAA26J69A5","localTimestamp":"2021-02-08T15:18:45.233Z","randomId":1672}
[35mplayout-gateway_1  |[0m {"level":"info","message":"Core: Setting up subscriptions..","localTimestamp":"2021-02-08T15:18:45.233Z","randomId":9408}
[35mplayout-gateway_1  |[0m {"level":"info","message":"DeviceId: BGHH649DAA26J69A5","localTimestamp":"2021-02-08T15:18:45.233Z","randomId":7324}
[36mcore_1             |[0m {"message":"syncFunction: v6kqWxzDNVYU2_YO5Xa8rIuFQ9o_ (checkBlueprintsConfig - checkBlueprintsConfig)","level":"debug"}
[36mcore_1             |[0m {"message":"Uncaught error happened in GUI\n  in \"http://localhost:3000/rundowns\"\n  on \"172.18.0.1\"\n  at 2021-02-08T15:19:07.566Z:\n[\"Error initializing i18Next\",[\"failed parsing /locales/en/translations.json to json\"]]","level":"error"}
Gracefully stopping... (press Ctrl+C again to force)

**Comment by mint-dewit** [comment]
> How do I run migration?

That's  described on the _initial setup_ page in our gitbook: https://sofie.gitbook.io/sofie-tv-automation/documentation/getting-started/installation/initial-sofie-core-setup

> Do i need to have already rundowns installed to that point?

No
