### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by toresbe** [nrkno/Sofie-TV-automation#54]
Hello, just a friendly heads-up – there are lots of broken links here:

https://nrkno.github.io/sofie-core/docs/for-developers/intro/

**Comment by mint-dewit** [comment]
HI, thanks for bringing this to our attention. It seems this may be an issue with Docusaurus when url's have a trailing slash. We'll look into upgrading our docusaurus version.

**Comment by mint-dewit** [comment]
We've figured out what the issue was and have fixed it now. Thanks again for reporting this!
