### ISSUE TITLE
How to install Sofie Automation GUI

### ISSUE THREAD

**Issue by mairajha** [nrkno/Sofie-TV-automation#7]
![Automation](https://user-images.githubusercontent.com/52917522/64440000-97d5c180-d0e4-11e9-9e68-c950885cdbec.jpg)
We just installed Sofie core (all gateways up and running fine) just wanted to know that how we will install Sofie GUI, can you please help us out?

**Comment by nytamin** [comment]
Hey there! We're working on getting the documentation together. Meanwhile, have a look at the Getting Started guide here: https://sofie.gitbook.io/sofie-tv-automation/documentation/getting-started
