### ISSUE TITLE
"MediaScanner: ECONNREFUSED"

### ISSUE THREAD

**Issue by angelognanamuthu** [nrkno/Sofie-TV-automation#9]
Hi I am trying to install Sofie with Google Spreadsheet support, but I am getting this message in widows powershell,
playout-gateway_1  | {"level":"warn","message":"MediaScanner: ECONNREFUSED","localTimestamp":"2019-09-28T21:45:38.295Z","randomId":1370}
Could you please help me solve this problem. Thank you. 

![sofie error](https://user-images.githubusercontent.com/38923573/65822776-af015e00-e20f-11e9-91fe-6c9645adecfc.png)

**Comment by nytamin** [comment]
Hello!
This means that the playout gateway can't connect to the casparcg media scanner.
We're moving that functionality from the playout gateway to Media Manager, so you can disable that feature by entering "disable" in the Media Scanner Host setting for that Playout Gateway (in the Sofie GUI)

**Comment by jesperstarkar** [comment]
Perhaps it should be disabled by default, if the `Host` is blank too?

**Comment by rogerbratseth** [comment]
> Hello!
> This means that the playout gateway can't connect to the casparcg media scanner.
> We're moving that functionality from the playout gateway to Media Manager, so you can disable that feature by entering "disable" in the Media Scanner Host setting for that Playout Gateway (in the Sofie GUI)

I have the same problem, but the installer seems to enter an endless loop. Do you mean that the GUI is available at this stage in the install-procedure?

**Comment by nytamin** [comment]
I believe this was fixed some time ago, feel free to reopen if it's still an issue.
